### ISSUE TITLE
InsertFile throws an error

### ISSUE THREAD

**Issue by americanslon** [fgilde/MudExRichTextEditor#3]
Clicking on insert file icon throws the following

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'FileService' on type 'MudBlazor.Extensions.Components.MudExUploadEdit`1[[MudBlazor.Extensions.Components.UploadableFile, MudBlazor.Extensions, Version=1.7.84.0, Culture=neutral, PublicKeyToken=null]]'. There is no registered service of type 'MudBlazor.Extensions.Services.MudExFileService'.
System.InvalidOperationException: Cannot provide a value for property 'FileService' on type 'MudBlazor.Extensions.Components.MudExUploadEdit`1[[MudBlazor.Extensions.Components.UploadableFile, MudBlazor.Extensions, Version=1.7.84.0, Culture=neutral, PublicKeyToken=null]]'. There is no registered service of type 'MudBlazor.Extensions.Services.MudExFileService'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by fgilde** [comment]
you need to add the required MudExtensions services

```
 builder.Services.AddMudServicesWithExtensions();
```

**Comment by americanslon** [comment]
Makes sense, I thought the installation was too simple to be everything.
May want to add that line to the installation instructions. 

Thanks!

**Comment by fgilde** [comment]
You’re right 👍

americanslon ***@***.***> schrieb am Di. 5. März 2024 um
19:41:
